apiVersion: v1
kind: Secret
metadata:
  name: presta-secret
  namespace: prestans
type: Opaque
stringData:
  PRESTASHOP_DATABASE_NAME: {{ .Values.config.dbname }}
  PRESTASHOP_DATABASE_USER: {{ .Values.config.dbuser }}
  PRESTASHOP_DATABASE_PASSWORD: {{ .Values.config.dbpass }}
  MARIA_ROOT_PWD: {{ .Values.config.dbadminpwd }}
  PRESTASHOP_PASSWORD: {{ .Values.config.adminpass }}
  PRESTASHOP_EMAIL: {{ .Values.config.adminmail }}
  