apiVersion: v1
kind: Service
metadata:
  name: prestashop-svc
  namespace: prestans
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.config.externalport }}
    protocol: TCP
  selector:
    app: prestashop